language: php
php:
  - "5.5"
  - "5.4"

before_script:
  - composer self-update
  - composer install
  - printf "\n" | pecl install pecl_http-1.7.6


script: ./phpunit --configuration ./tests/travis-ci.xml
